services:
  derive:
    build: .
    image: derive
    container_name: derive
    ports:
      - "${PORT}:3000"
    volumes:
      - data:/app/data
      - ./src:/app/src
    restart: unless-stopped

volumes:
  data:
